### PR TITLE
upgrade to CXF 3 & Spring 4 with cleaner codegen and testing pre-condition

### PR DESCRIPTION
**Pull request by cbismuth**
We use Fuel SDK for Java in production and made some improvements, commit logs are quite explicit.

### CODE REVIEW

**Comment by cbismuth** [comment]
@imurdock should I update this PR or is it worthless? thanks

**Comment by imurdock** [comment]
Hi Christophe,

I've cherry-picked most of your pull request into the v1.1 branch already, and your note reminded me I still need to reconcile your pom.xml changes with my own, which I'll do tomorrow.

Thanks!

-ian

**Comment by cbismuth** [comment]
That's really nice, thank you Ian :smile:

**Comment by cbismuth** [comment]
Related to the ability to disable tests when no fuel configuration is available, a base test class should be created to centralize the `setUpBeforeClass` method.

I'll checkout branch 1.1 and do this as soon as I can.

++
Chris

**Comment by imurdock** [comment]
The update to Apache CXF 3 has been merged. Please resubmit a finer-grained pull request if you want some or all of the other changes merged. Thanks! -ian

**Comment by cbismuth** [comment]
Thanks Ian.

**Pull request closed without merging**
